In [1]:
# Add the two matrices element-wise
import numpy as np
m1=np.array([[1,4],[-5,8]])
m2=np.array([[7,-6],[-11,2]])
msum=m1+m2
print(msum)

[[  8  -2]
 [-16  10]]


In [2]:
# Compute the matrix product using the dot product
product=np.dot(m1,m2)
print(product) 

[[ -37    2]
 [-123   46]]


In [3]:
# Create a 2x3 matrix filled with zeros
zero=np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
 #Create a 3x3 identity matrix
identity=np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import matplotlib.pyplot as plt 
from mpl_toolkist.mplot import Axes3D

In [12]:
import numpy as np
n=2
a=np.random.randn(n,n)
b=np.random.randn(n,n)
c=np.random.randn(n,n)
s1=np.dot( a , np.dot(b,c))
s2=np.dot(np.dot(a,b) , c)
print(s1)
print(s2)


[[-0.79499644 -0.10774263]
 [-0.18623996 -0.04431087]]
[[-0.79499644 -0.10774263]
 [-0.18623996 -0.04431087]]


In [14]:
import numpy as np
n=1
a=np.random.randn(n)
b=np.random.randn(n)
c=np.random.randn(n)
s1=np.dot( a , np.dot(b,c))
s2=np.dot(np.dot(a,b) , c)
print(s1)
print(s2)

[-0.42234853]
[-0.42234853]


In [15]:
import numpy as np
n=3
a=np.random.randn(n,n,n)
b=np.random.randn(n,n,n)
c=np.random.randn(n,n,n)
s1=np.dot( a , np.dot(b,c))
s2=np.dot(np.dot(a,b) , c)
print(s1)
print(s2)

[[[[[ 0.65007273 -2.33002644 -1.71575913]
    [ 1.61274046  0.97271922 -0.5164717 ]
    [-1.65721862 -0.35574667  0.86165644]]

   [[ 1.13839557  0.66532558 -0.36218883]
    [ 0.98746512 -3.05851102 -2.31016628]
    [-1.64347112 -0.53590081  0.77733324]]

   [[ 1.41529759 -0.46548837 -1.18195682]
    [-1.6438668   2.23167844  2.31155353]
    [ 1.44837018 -4.62753313 -3.51579925]]]


  [[[-0.37966862  2.54115905  2.11305443]
    [-1.12999105 -1.57301695  0.45404729]
    [ 1.6281103   0.83664185 -1.19737454]]

   [[-1.06530342 -1.06958581  0.48737654]
    [-1.15421865  3.3326906   3.18799741]
    [ 1.1609178   1.07053116 -0.79804462]]

   [[-0.98988313  0.16033164  1.35352937]
    [ 1.06127889 -2.15625643 -2.74767826]
    [-0.7610712   4.99812325  4.25128766]]]


  [[[ 0.19523438 -0.89732999  0.08677293]
    [-0.16947617  0.58666166 -0.49402985]
    [-0.78555421  0.12385601  0.08641744]]

   [[ 0.37890313  0.15155217 -0.15084889]
    [ 1.29400055 -1.69624625  0.49270073]
    [ 0.0877616 

In [13]:
import numpy as np

n = 2
a = np.random.randn(n, n)
b = np.random.randn(n, n)
c = np.random.randn(n, n)

# Compute s1 and s2
s1 = np.dot(a, np.dot(b, c))  # Matrix multiplication: a * (b * c)
s2 = np.dot(np.dot(a, b), c)  # Matrix multiplication: (a * b) * c

# Print results
print("a:\n", a)
print("b:\n", b)
print("c:\n", c)
print("s1:\n", s1)
print("s2:\n", s2)

# Check if they are the same
are_equal = np.allclose(s1, s2)
print("s1 and s2 are equal:", are_equal)


a:
 [[ 0.20294003  0.25718815]
 [-2.52188703 -0.41261833]]
b:
 [[ 1.37828463 -1.39875553]
 [-0.18325021  1.19750969]]
c:
 [[ 1.00761375 -0.82250625]
 [ 0.51088442  1.39653523]]
s1:
 [[ 0.2466736  -0.15761099]
 [-1.87644331  7.03297438]]
s2:
 [[ 0.2466736  -0.15761099]
 [-1.87644331  7.03297438]]
s1 and s2 are equal: True
